//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace GuardianReviews.Domain.Model
{
    public class Review
    {
        protected Review()
        {
            
        }
        public Review(ReviewTypes type)
        {
            ReviewType = type;
        }
        public virtual int Id
        {
            get;
            protected set;
        }
        public virtual string Title
        {
            get;
            set;
        }
        public virtual string Body
        {
            get;
            set;
        }
        public virtual DateTime PublicationDate
        {
            get;
            set;
        }
        public virtual ReviewTypes ReviewType
        {
            get;
            protected set;
        }
        public virtual int? StarRating
        {
            get;
            set;
        }
        public virtual string WebUrl
        {
            get;
            set;
        }
    }
}
