//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace GuardianReviews.Domain.Model
{
    public class Review
    {
        public virtual string Id
        {
            get;
            set;
        }
        public virtual string Title
        {
            get;
            set;
        }
        public virtual DateTime PublicationDate
        {
            get;
            set;
        }
        public virtual ReviewTypes ReviewType
        {
            get;
            set;
        }
        public virtual StarRatings? StarRating
        {
            get;
            set;
        }
        public virtual string WebUrl
        {
            get;
            set;
        }
    }
}
