//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace GuardianReviews.Domain
{
    public partial class Review
    {
        #region Primitive Properties
    
        public virtual string Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual System.DateTime PublicationDate
        {
            get;
            set;
        }
    
        public virtual int ReviewType
        {
            get;
            set;
        }
    
        public virtual Nullable<int> StarRating
        {
            get;
            set;
        }
    
        public virtual string WebUrl
        {
            get { return _webUrl; }
            set { _webUrl = value; }
        }
        private string _webUrl = "\"\"";

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<MusicType> MusicTypes
        {
            get
            {
                if (_musicTypes == null)
                {
                    var newCollection = new FixupCollection<MusicType>();
                    newCollection.CollectionChanged += FixupMusicTypes;
                    _musicTypes = newCollection;
                }
                return _musicTypes;
            }
            set
            {
                if (!ReferenceEquals(_musicTypes, value))
                {
                    var previousValue = _musicTypes as FixupCollection<MusicType>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMusicTypes;
                    }
                    _musicTypes = value;
                    var newValue = value as FixupCollection<MusicType>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMusicTypes;
                    }
                }
            }
        }
        private ICollection<MusicType> _musicTypes;

        #endregion
        #region Association Fixup
    
        private void FixupMusicTypes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (MusicType item in e.NewItems)
                {
                    if (!item.Reviews.Contains(this))
                    {
                        item.Reviews.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MusicType item in e.OldItems)
                {
                    if (item.Reviews.Contains(this))
                    {
                        item.Reviews.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
